name: Forge Linter

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Run linter and check for errors
        id: lint
        run: forge fmt --check
